### ISSUE TITLE
Paket doesn't install LightningDB

### ISSUE THREAD

**Issue by elanperach** [zenprotocol/ZFS-SDK#1]
Paket failed with
-> Package LightningDB was referenced in /home/elan/programming/apps/zen/ZFS-SDK/paket-files/gitlab.com/zenprotocol/zenprotocol/src/DataAccess/DataAccess.fsproj, but it was not found in the paket.lock file in group Main.

**Comment by A-Manning** [comment]
This bug no longer occurs. Closing.
