### ISSUE TITLE
Zebra does not display command line output from ZF*

### ISSUE THREAD

**Issue by A-Manning** [zenprotocol/ZFS-SDK#17]
This is caused by using `Platform.run` from `zenprotocol`'s `Infrastructure` module, which redirects output to a logger.
Fix is to invoke ZF* directly from zebra

**Comment by arielzenprotocol** [comment]
Resolved by [ba7c7603c4c19c81b7f2fd7568db4435358596b5](https://github.com/zenprotocol/ZFS-SDK/commit/ba7c7603c4c19c81b7f2fd7568db4435358596b5)
